/** @type {GalleryItem[]} */
export const galleryItems = [
  {
    id: 'mariage-avignon-2025-machine-a-fumee',
    src: '/elements/gallery/mariage-avignon-2025-machine-a-fumee.jpg',
    alt: 'DJ Mika accompagne l’ouverture de bal d’un mariage à Avignon avec fumée lourde et lumières',
    caption: 'Mariage — ouverture de bal',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
  {
    id: 'anniversaire-50-ans-loriol-2026',
    src: '/elements/gallery/anniversaire-50-ans-loriol-2026.jpg',
    alt: 'Installation DJ Mika pour un anniversaire de 50 ans avec écran, sonorisation et décoration',
    caption: 'Anniversaire — 50 ans',
    orientation: 'landscape',
    width: 1536,
    height: 1152,
  },
  {
    id: 'anniversaire-jeunes-sorgues-2026',
    src: '/elements/gallery/anniversaire-jeunes-sorgues-2026.jpg',
    alt: 'Sonorisation et éclairage DJ Mika en extérieur pour l’anniversaire de Louis à Sorgues',
    caption: 'Anniversaire Louis — Sorgues',
    orientation: 'landscape',
    width: 1536,
    height: 1152,
  },
  {
    id: 'inauguration-ouverture-sephora-marseille-vieux-port',
    src: '/elements/gallery/inauguration-ouverture-sephora-marseille-vieux-port.jpg',
    alt: 'DJ Mika anime l’ouverture Sephora Marseille Terrasses du Port avec un set musical en magasin',
    caption: 'Corporate — Sephora Marseille Terrasses du Port',
    orientation: 'landscape',
    width: 1536,
    height: 1189,
  },
  {
    id: 'anniversaire-18ans-jeunes-ambiances-lumiere',
    src: '/elements/gallery/anniversaire-18ans-jeunes-ambiances-lumiere.jpg',
    alt: 'Ambiance lumineuse bleue et installation DJ Mika pour la soirée Yogan',
    caption: 'Yogan — ambiance lumineuse',
    orientation: 'landscape',
    width: 1536,
    height: 1152,
  },
  {
    id: 'mariage-avignon-2025-machine-etincelles-artifice',
    src: '/elements/gallery/mariage-avignon-2025-machine-etincelles-artifice.jpg',
    alt: 'Ouverture de bal avec DJ Mika, machine à étincelles et ambiance chaleureuse de mariage',
    caption: 'Mariage — étincelles froides',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
  {
    id: 'soiree-nouvel-an-2026-zanzibar-sete',
    src: '/elements/gallery/soiree-nouvel-an-2026-zanzibar-sete.jpg',
    alt: 'DJ Mika mixe une soirée du Nouvel An au Zanzibar à Sète avec ambiance club et karaoké',
    caption: 'Nouvel An — Zanzibar Sète',
    orientation: 'landscape',
    width: 1536,
    height: 940,
  },
  {
    id: 'mariage-dansant-lumieres',
    src: '/elements/gallery/mariage-dansant-lumieres.jpg',
    alt: 'Invités dansent sous les jeux de lumières de DJ Mika lors d’une soirée de mariage',
    caption: 'Mariage — piste de danse',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
  {
    id: 'mariage-interieur-lumieres-dynamiques',
    src: '/elements/gallery/mariage-interieur-lumieres-dynamiques.jpg',
    alt: 'DJ Mika en prestation de mariage avec éclairages dynamiques et sonorisation professionnelle',
    caption: 'Mariage — DJ en action',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
  {
    id: 'mariage-laura-maxime-ceremonie-piscine',
    src: '/elements/gallery/mariage-laura-maxime-ceremonie-piscine.webp',
    alt: 'Sonorisation de cérémonie laïque au bord de la piscine pour le mariage de Laura et Maxime',
    caption: 'Mariage Laura & Maxime — cérémonie piscine',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'mariage-laura-maxime-exterieur',
    src: '/elements/gallery/mariage-laura-maxime-exterieur.webp',
    alt: 'Ambiance musicale en extérieur lors du mariage de Laura et Maxime',
    caption: 'Mariage Laura & Maxime — extérieur',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'mariage-laura-maxime-exterieur-animation',
    src: '/elements/gallery/mariage-laura-maxime-exterieur-animation.webp',
    alt: 'Animation DJ en extérieur pendant le mariage de Laura et Maxime',
    caption: 'Mariage Laura & Maxime — animation',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'mariage-laura-maxime-soiree-nuit',
    src: '/elements/gallery/mariage-laura-maxime-soiree-nuit.webp',
    alt: 'Soirée dansante de nuit animée par DJ Mika au mariage de Laura et Maxime',
    caption: 'Mariage Laura & Maxime — soirée',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'mariage-oceane-anthony-valence-repas',
    src: '/elements/gallery/mariage-oceane-anthony-valence-repas.webp',
    alt: 'Sonorisation d’ambiance pendant le repas du mariage d’Océane et Anthony près de Valence',
    caption: 'Mariage Océane & Anthony — repas',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'mariage-oceane-anthony-soiree-dansante',
    src: '/elements/gallery/mariage-oceane-anthony-soiree-dansante.webp',
    alt: 'Piste de danse animée lors du mariage d’Océane et Anthony en région lyonnaise',
    caption: 'Mariage Océane & Anthony — soirée dansante',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'mariage-gaetan-audrey-domaine-viticole-lyon',
    src: '/elements/gallery/mariage-gaetan-audrey-domaine-viticole-lyon.webp',
    alt: 'Buffet dinatoire et ambiance musicale au mariage de Gaëtan et Audrey dans un domaine viticole près de Lyon',
    caption: 'Mariage Gaëtan & Audrey — domaine viticole',
    orientation: 'landscape',
    width: 1400,
    height: 963,
  },
  {
    id: 'mariage-gaetan-audrey-soiree-dansante',
    src: '/elements/gallery/mariage-gaetan-audrey-soiree-dansante.webp',
    alt: 'Soirée dansante animée par DJ Mika au mariage de Gaëtan et Audrey',
    caption: 'Mariage Gaëtan & Audrey — soirée dansante',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'anniversaire-18-ans-fiona-montpellier-exterieur',
    src: '/elements/gallery/anniversaire-18-ans-fiona-montpellier-exterieur.webp',
    alt: 'Sonorisation d’apéritif et repas en extérieur pour l’anniversaire 18 ans de Fiona près de Montpellier, le 11 juillet 2026',
    caption: 'Anniversaire Fiona 18 ans — 11 juillet 2026, extérieur',
    orientation: 'landscape',
    width: 2600,
    height: 1950,
  },
  {
    id: 'anniversaire-18-ans-fiona-montpellier-piste',
    src: '/elements/gallery/anniversaire-18-ans-fiona-montpellier-piste.webp',
    alt: 'Animation soirée dansante en intérieur pour l’anniversaire 18 ans de Fiona, le 11 juillet 2026',
    caption: 'Anniversaire Fiona 18 ans — 11 juillet 2026, piste',
    orientation: 'landscape',
    width: 1800,
    height: 1350,
  },
  {
    id: 'anniversaire-18-ans-mathys-saint-cyr-sur-mer-ambiance',
    src: '/elements/gallery/anniversaire-18-ans-mathys-saint-cyr-sur-mer-ambiance.jpeg',
    alt: 'Ambiance bleue et soirée dansante pour l’anniversaire 18 ans de Mathys à Saint-Cyr-sur-Mer',
    caption: 'Anniversaire Mathys 18 ans — ambiance',
    orientation: 'landscape',
    width: 5712,
    height: 4284,
  },
  {
    id: 'anniversaire-18-ans-mathys-saint-cyr-sur-mer-drag-queen',
    src: '/elements/gallery/anniversaire-18-ans-mathys-saint-cyr-sur-mer-drag-queen.jpeg',
    alt: 'Spectacle drag queen Aquarii lors de l’anniversaire 18 ans de Mathys à Saint-Cyr-sur-Mer',
    caption: 'Anniversaire Mathys 18 ans — drag queen',
    orientation: 'landscape',
    width: 5712,
    height: 4284,
  },
  {
    id: 'anniversaire-30-ans-canelle-marseille-plein-air',
    src: '/elements/gallery/anniversaire-30-ans-canelle-marseille-plein-air.webp',
    alt: 'Anniversaire 30 ans de Canelle en plein air à Marseille avec ambiance réunionnaise et animation vidéo',
    caption: 'Anniversaire Canelle 30 ans — Marseille',
    orientation: 'landscape',
    width: 1600,
    height: 1200,
  },
  {
    id: 'inauguration-entreprise-frejus-exterieur',
    src: '/elements/gallery/inauguration-entreprise-frejus-exterieur.webp',
    alt: 'Buffet dinatoire en extérieur pour l’inauguration de nouveaux locaux d’entreprise à Fréjus',
    caption: 'Inauguration entreprise — Fréjus',
    orientation: 'landscape',
    width: 1500,
    height: 1125,
  },
  {
    id: 'inauguration-entreprise-frejus-buffet-annees-80',
    src: '/elements/gallery/inauguration-entreprise-frejus-buffet-annees-80.webp',
    alt: 'Ambiance musicale années 80 lors de l’inauguration d’entreprise à Fréjus',
    caption: 'Inauguration entreprise — années 80',
    orientation: 'landscape',
    width: 1500,
    height: 844,
  },
  {
    id: 'soiree-restaurant-lac-alaiade-beaumont-de-pertuis',
    src: '/elements/gallery/soiree-restaurant-lac-alaiade-beaumont-de-pertuis.webp',
    alt: 'Ambiance musicale au restaurant Lac Alaiade à Beaumont-de-Pertuis, le 14 août 2026',
    caption: 'Soirée restaurant Lac Alaiade — 14 août 2026',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'soiree-restaurant-lac-alaiade-piste-danse',
    src: '/elements/gallery/soiree-restaurant-lac-alaiade-piste-danse.webp',
    alt: 'Soirée dansante animée par DJ Mika au restaurant Lac Alaiade, le 14 août 2026',
    caption: 'Soirée restaurant Lac Alaiade — 14 août 2026, piste',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'fete-petanque-sardinade-barbecue-montpellier',
    src: '/elements/gallery/fete-petanque-sardinade-barbecue-montpellier.webp',
    alt: 'Soirée sardinade barbecue et ambiance dansante pour la fête annuelle d’un club de pétanque près de Montpellier',
    caption: 'Fête annuelle pétanque — sardinade',
    orientation: 'landscape',
    width: 1400,
    height: 1050,
  },
  {
    id: 'drag-queen-aquarii-animation',
    src: '/elements/photos/prestations/drag-queen-aquarii-animation.webp',
    alt: 'Spectacle drag queen Aquarii proposé parmi les animations Private Events',
    caption: 'Prestation — drag queen Aquarii',
    orientation: 'square',
    width: 1440,
    height: 1440,
  },
  {
    id: 'videobooth-souvenirs-soiree',
    src: '/elements/photos/prestations/videobooth-souvenirs-soiree.webp',
    alt: 'Vidéobooth pour capturer des souvenirs vidéo lors d’une soirée Private Events',
    caption: 'Prestation — vidéobooth',
    orientation: 'landscape',
    width: 1536,
    height: 1024,
  },
];
