/** @type {GalleryItem[]} */
export const galleryItems = [
  {
    id: 'mariage-avignon-2025-machine-a-fumee',
    src: '/elements/gallery/mariage-avignon-2025-machine-a-fumee.jpg',
    alt: 'DJ Mika accompagne l’ouverture de bal d’un mariage à Avignon avec fumée lourde et lumières',
    caption: 'Mariage — ouverture de bal',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
  {
    id: 'anniversaire-50-ans-loriol-2026',
    src: '/elements/gallery/anniversaire-50-ans-loriol-2026.jpg',
    alt: 'Installation DJ Mika pour un anniversaire de 50 ans avec écran, sonorisation et décoration',
    caption: 'Anniversaire — 50 ans',
    orientation: 'landscape',
    width: 1536,
    height: 1152,
  },
  {
    id: 'anniversaire-jeunes-sorgues-2026',
    src: '/elements/gallery/anniversaire-jeunes-sorgues-2026.jpg',
    alt: 'Sonorisation et éclairage DJ Mika en extérieur pour un anniversaire privé à Sorgues',
    caption: 'Anniversaire — extérieur',
    orientation: 'landscape',
    width: 1536,
    height: 1152,
  },
  {
    id: 'inauguration-ouverture-sephora-marseille-vieux-port',
    src: '/elements/gallery/inauguration-ouverture-sephora-marseille-vieux-port.jpg',
    alt: 'DJ Mika anime l’ouverture Sephora Marseille Terrasses du Port avec un set musical en magasin',
    caption: 'Corporate — Sephora Marseille Terrasses du Port',
    orientation: 'landscape',
    width: 1536,
    height: 1189,
  },
  {
    id: 'anniversaire-18ans-jeunes-ambiances-lumiere',
    src: '/elements/gallery/anniversaire-18ans-jeunes-ambiances-lumiere.jpg',
    alt: 'Ambiance lumineuse bleue et installation DJ Mika pour un anniversaire de 18 ans',
    caption: 'Anniversaire — 18 ans',
    orientation: 'landscape',
    width: 1536,
    height: 1152,
  },
  {
    id: 'mariage-avignon-2025-machine-etincelles-artifice',
    src: '/elements/gallery/mariage-avignon-2025-machine-etincelles-artifice.jpg',
    alt: 'Ouverture de bal avec DJ Mika, machine à étincelles et ambiance chaleureuse de mariage',
    caption: 'Mariage — étincelles froides',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
  {
    id: 'soiree-nouvel-an-2026-zanzibar-sete',
    src: '/elements/gallery/soiree-nouvel-an-2026-zanzibar-sete.jpg',
    alt: 'DJ Mika mixe une soirée du Nouvel An au Zanzibar à Sète avec ambiance club et karaoké',
    caption: 'Nouvel An — Zanzibar Sète',
    orientation: 'landscape',
    width: 1536,
    height: 940,
  },
  {
    id: 'mariage-dansant-lumieres',
    src: '/elements/gallery/mariage-dansant-lumieres.jpg',
    alt: 'Invités dansent sous les jeux de lumières de DJ Mika lors d’une soirée de mariage',
    caption: 'Mariage — piste de danse',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
  {
    id: 'mariage-interieur-lumieres-dynamiques',
    src: '/elements/gallery/mariage-interieur-lumieres-dynamiques.jpg',
    alt: 'DJ Mika en prestation de mariage avec éclairages dynamiques et sonorisation professionnelle',
    caption: 'Mariage — DJ en action',
    orientation: 'portrait',
    width: 1024,
    height: 1536,
  },
];